
version: '3.7'
services:
  app:
    container_name: lafs-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_NAME=lafs-db
  mongo:
    container_name: lafs-db
    image: 'mongo:4'
    ports:
      - '27017:27018'
networks:
  default:
    external: true
    name: lafs-net